---
- hosts: all
  become: true
  tasks:
    - name: Shutdown Ubuntu (Debian) related instances alone
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"
