--- 
- name: Enforce s3 bucket versioning on AWS account 
  hosts: localhost
  gather_facts: false # Will disable the gathering facts, as we are not doing infra (no inventory.ini)
  connection: local
  tasks:
    - name: List S3 buckets for the AWS Account
      amazon.aws.s3_bucket_info:
      register: result
    - name: Listing the buckets
      ansible.builtin.debug:
        msg: "{{ result['buckets'] }}"
    - debug: ### detailed info
        var: result
    - name: Enable Versioning on S3 buckets
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: yes
      loop: "{{ result.buckets }}"
